import { Trip, Settlement, Person } from '../types';
import { formatAmount } from './currency';

export interface ShareOptions {
  language: 'zh-TW' | 'en';
}

export const generateSettlementMessage = (
  trip: Trip,
  settlements: Settlement[],
  options: ShareOptions
): string => {
  const { language } = options;
  const isZh = language === 'zh-TW';
  
  // Calculate total expenses
  const totalExpenses = trip.expenses.reduce((sum, expense) => sum + expense.amount, 0);
  
  // Build message
  const lines: string[] = [];
  
  // Header
  lines.push(isZh ? '📊 旅行分帳結果' : '📊 Trip Settlement');
  lines.push(isZh ? `行程：${trip.name}` : `Trip: ${trip.name}`);
  lines.push('');
  
  // Participants
  const participantNames = trip.people.map(p => p.name).join(', ');
  lines.push(isZh ? `👥 參與者: ${participantNames}` : `👥 Participants: ${participantNames}`);
  
  // Total
  lines.push(isZh ? `💰 總花費: ${formatAmount(totalExpenses, trip.currency, language)}` : `💰 Total Expenses: ${formatAmount(totalExpenses, trip.currency, language)}`);
  
  // Dates
  lines.push(isZh ? `📅 日期: ${trip.startDate} ~ ${trip.endDate}` : `📅 Dates: ${trip.startDate} ~ ${trip.endDate}`);
  lines.push('');
  
  // Settlement plan
  if (settlements.length > 0) {
    lines.push(isZh ? '💸 結算方案:' : '💸 Settlement Plan:');
    settlements.forEach(settlement => {
      const fromPerson = trip.people.find(p => p.id === settlement.from);
      const toPerson = trip.people.find(p => p.id === settlement.to);
      if (fromPerson && toPerson) {
        const arrow = isZh ? '→' : 'pays';
        lines.push(`• ${fromPerson.name} ${arrow} ${toPerson.name}: ${formatAmount(settlement.amount, trip.currency, language)}`);
        
        // Add bank info if available
        if (toPerson.bankInfo) {
          lines.push(`  ${isZh ? '帳戶' : 'Account'}: ${toPerson.bankInfo.bankName} ${toPerson.bankInfo.accountNumber}`);
        }
      }
    });
  } else {
    lines.push(isZh ? '✅ 所有帳目已結清！' : '✅ All settled up!');
  }
  
  lines.push('');
  lines.push(isZh ? '⏰ 請於 7 天內完成轉帳，謝謝！' : '⏰ Please settle within 7 days. Thank you!');
  lines.push('');
  lines.push(isZh ? '📱 由 TravelSplit 旅行分帳神器 產生' : '📱 Generated by TravelSplit');
  
  return lines.join('\n');
};

export const generateReminderMessage = (
  fromPerson: Person,
  toPerson: Person,
  amount: number,
  currency: string,
  tripName: string,
  options: ShareOptions
): string => {
  const { language } = options;
  const isZh = language === 'zh-TW';
  
  const lines: string[] = [];
  
  if (isZh) {
    lines.push(`👋 嗨 ${fromPerson.name},`);
    lines.push('');
    lines.push(`這是一個友善的提醒，關於「${tripName}」的分帳：`);
    lines.push('');
    lines.push(`你需要付給 ${toPerson.name}: ${formatAmount(amount, currency, language)}`);
    
    if (toPerson.bankInfo) {
      lines.push('');
      lines.push('🏦 轉帳資訊:');
      lines.push(`銀行: ${toPerson.bankInfo.bankName}`);
      lines.push(`帳號: ${toPerson.bankInfo.accountNumber}`);
    }
    
    lines.push('');
    lines.push('謝謝！ 😊');
  } else {
    lines.push(`👋 Hi ${fromPerson.name},`);
    lines.push('');
    lines.push(`This is a friendly reminder about "${tripName}" expenses:`);
    lines.push('');
    lines.push(`You need to pay ${toPerson.name}: ${formatAmount(amount, currency, language)}`);
    
    if (toPerson.bankInfo) {
      lines.push('');
      lines.push('🏦 Transfer Info:');
      lines.push(`Bank: ${toPerson.bankInfo.bankName}`);
      lines.push(`Account: ${toPerson.bankInfo.accountNumber}`);
    }
    
    lines.push('');
    lines.push('Thanks! 😊');
  }
  
  lines.push('');
  lines.push(isZh ? '📱 由 TravelSplit 旅行分帳神器 產生' : '📱 Generated by TravelSplit');
  
  return lines.join('\n');
};

export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    document.body.appendChild(textArea);
    textArea.select();
    try {
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return true;
    } catch (err) {
      document.body.removeChild(textArea);
      return false;
    }
  }
};

export const shareViaLine = (message: string): void => {
  const encodedMessage = encodeURIComponent(message);
  window.open(`https://line.me/R/share?text=${encodedMessage}`, '_blank');
};

export const shareViaWhatsApp = (message: string): void => {
  const encodedMessage = encodeURIComponent(message);
  window.open(`https://wa.me/?text=${encodedMessage}`, '_blank');
};

export const shareViaEmail = (subject: string, body: string): void => {
  const encodedSubject = encodeURIComponent(subject);
  const encodedBody = encodeURIComponent(body);
  window.open(`mailto:?subject=${encodedSubject}&body=${encodedBody}`);
};

export const shareViaNative = async (title: string, text: string): Promise<boolean> => {
  if (navigator.share) {
    try {
      await navigator.share({
        title,
        text,
      });
      return true;
    } catch (error) {
      // User cancelled or error occurred
      return false;
    }
  }
  return false;
};
